---
apiVersion: v1
kind: Service
metadata:
  name: slack-talkers
  labels:
    run: slack-talkers
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: slack-talkers

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slack-talkers
  labels:
    run: slack-talkers
spec:
  replicas: 2
  selector:
    matchLabels:
      run: slack-talkers
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: slack-talkers
    spec:
      containers:
      - name: slack-talkers
        image: ssanders0/slack-talkers:0.0.3
        imagePullPolicy: Always
        env:
        - name: SLACK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-api-token
              key: SLACK_API_TOKEN
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
