resources:
- name: slack-talkers-repository
  type: git
  source:
    uri: git@github.com:p-ssanders/slack-talkers.git
    branch: master
    private_key: ((git-deploy-key.private_key))

- name: slack-talkers-docker-image
  type: docker-image
  source:
    repository: ssanders0/slack-talkers
    username: ssanders0
    password: ((dockerhub-password))

- name: docker-tag
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:p-ssanders/slack-talkers.git
    branch: master
    private_key: ((git-deploy-key.private_key))
    file: docker-tag


jobs:
- name: test
  plan:
  - get: slack-talkers-repository
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 11-jdk-slim
      inputs:
      - name: slack-talkers-repository
      run:
        path: bash
        args:
        - "-c"
        - |
          set -eux
          cd slack-talkers-repository
          ./mvnw test

- name: build
  plan:
    - get: slack-talkers-repository
      passed:
      - test
      trigger: true
    - get: docker-tag
      params:
        bump: minor
    - task: package
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: openjdk
            tag: 11-jdk-slim
        inputs:
        - name: slack-talkers-repository
        outputs:
        - name: workspace
        run:
          path: bash
          args:
          - "-c"
          - |
            set -eux
            cd slack-talkers-repository
            ./mvnw -DskipTests package
            cp -r * ../workspace
    - put: docker-image-version
    - put: slack-talkers-docker-image
      params:
        build: workspace
        tag_file: slack-talkers-repository/docker-tag
